

import { SideNav } from "./_components/SideNav";
import { Header } from "./_components/Header";
import { ThemeProvider } from "../../lib/theme-provider";




export const metadata = {
  title: "App Dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}) {
  return (
    <html lang="en">
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
      <body className={` min-h-screen dark:bg-zinc-950`}>
        <div className="md:w-64 fixed hidden md:block">
          <SideNav />
        </div>
        <div className="md:ml-64  flex flex-col bg-white   justify-between min-h-screen">
          <Header />
      
          <div className="flex-1">{children}</div>
        </div>
      </body>
      </ThemeProvider>
    </html>
  );
}
